### ISSUE TITLE
Variable types that include parenthesis have three different highlights

### ISSUE THREAD

**Issue by Ben-Voris** [manoutoftime/vscode_tal#3]
Several TAL data type names include parenthesis: `unsigned(n)`, `int(16)`, `int(32)`, `int(64)`, fixed(n), and `real(64)` These are displayed with three different highlights. The first part (e.g., `int`) is bold. The parenthesis have no apparent highlighting and the numbers are highlighted in red.

Note that `fixed(n)` allows `n` to be negative, so both `fixed(-3)` and `fixed(3)` are valid.

Please consider applying the same highlighting to the entire type. For example: **int(16)**.

**Comment by manoutoftime** [comment]
This one is actually expected, but maybe not too desired (?).

A year or so ago VSCode added language token inspector, which is great. Because before that writing language grammar was like trying to determine a shape of an object by touch in a dark room.

To bring it up: F1 -> Inspect Editor Token.
Then you can click on any language element and it will tell you how it's characterized (textmate scope). This is what themes use. They assign a colour to these textmate scopes.

What happens in this extension is:

- Keywords, such as **int**, **unsigned**, **string** and so on, are highlighted as textmate scope **storage.type.tal**. This is correct.
- Then parenthesis are not highlighted at all. There is no textmate scope assigned to them. This is questionable.
- Then what is inside parenthesis is processed on it's own. Digits are highlighted as textmate scope **constant.numeric.tal**. This is OK. It keeps things simple.

![image](https://user-images.githubusercontent.com/447868/89478262-80bcab00-d75d-11ea-94ba-16757af58b88.png)

For parenthesis it's matter of picking correct textmate scope. There is no official scope listed. But at least Python uses the following:
- function call ( - punctuation.definition.arguments.begin.python
- function call ) - punctuation.definition.arguments.end.python
- class inheritance ( - punctuation.definition.inheritance.begin.python
- class inheritance ) - punctuation.definition.inheritance.end.python
- ( by itself - punctuation.parenthesis.begin.python
- ) by itself - punctuation.parenthesis.end.python

Basic punctuation.parenthesis.begin.tal and punctuation.parenthesis.end.tal are probably good enough.

**Comment by manoutoftime** [comment]
I added a patch for this. I'll push it tomorrow. It's not too rigid. Digits and normal literals can apparently go in there.
E.g. this will compile:
literal width = 16;
int(width) foo;

https://github.com/manoutoftime/vscode_tal/compare/0.0.8_dev
